---
title: "Markov Text Model"
author: "Yile Shi, Letian Yin and Danni Chen"
date: "2021/10/4"
output:
  pdf_document: default
  html_document: default
---

## Step 3
```{r}
# Change working dictionary and read file to R
setwd("E:/Edi/StP/StP-practical_1-Gourp_8")
Bible <- scan(file = "Bible.txt", what = "character", skip = 157, fileEncoding = "UTF-8")
n_Bible <- length(Bible)
Bible <- Bible[-((n_Bible - 2909) : n_Bible)]
Sys.setlocale('LC_ALL', 'English_United States.1252')
```

## Step 4
```{r}
# Create function split_punct() to seperate punctuation marks and words
split_punct <- function(text){
  # index_punct <- NULL
  # punct <- c(",$", "\\.$", ";$", "!$", ":$", "\\?$")
  # for (i in 1 : length(punct)) {
  #   index_punct[[i]]<- grep(punct[i], text)
  # }
  # index_punct <- sort(unlist(index_punct, use.names = FALSE))
  index_punct <- grep("[,$, \\.$, ;$, !$, :$, \\?$]", text, fixed = FALSE )
  index_punct_new <- index_punct + 1:length(index_punct)
  text_new <- rep(" ", length(index_punct) + length(text))
  text_new[index_punct_new] <- substr(text[index_punct], nchar(text)[index_punct], nchar(text)[index_punct])
  text_word <- gsub("[,$, \\.$, ;$, !$, :$, \\?$]", "", text, fixed = FALSE)
  #text_new[index_punct_new - 1] <- substr(text[index_punct], 1, nchar(text)[index_punct] - 1)
  text_new[-index_punct_new] <- text_word
  return(text_new)
}

```

## Step 5
```{r}
# Use split_punct() to get new text
Bible_new <- split_punct(Bible)
```

## Step 6
```{r}
# Find 1000 most common words and store them in vector b
b <- NULL
Bible_lower <- tolower(Bible_new)
Bible_unique <- unique(Bible_lower)
index_unique <- match(Bible_lower, Bible_unique)
appearance <- tabulate(index_unique)
threshold <- head(sort(appearance, decreasing = TRUE),1000)[1000]
loc_1000 <- which(appearance >= threshold)
b <- Bible_unique[loc_1000]
```

## Step 7 
```{r}
# Create a index matrix whose 1st col is the index of each common words and 2nd col is the index of corresponding following words
index_b <- match(Bible_lower, b)
index_bind <- cbind(index_b[1 : length(index_b) - 1], index_b[2 : length(index_b)])
narows_b <- which(is.na(rowSums(index_bind) == TRUE))
index_bind <- index_bind[-narows_b,]

# Create matrix A 
A <-matrix(0, nrow = length(b), ncol = length(b))
row_bind <- nrow(index_bind)
for (i in 1 : row_bind){
  A[index_bind[i, 1], index_bind[i, 2]] = A[index_bind[i, 1], index_bind[i, 2]] + 1
}
rownames(A) <- b
rownames(A) <- b

# Standardize A 
A <- A/rowSums(A)
```

## Step 8
```{r}
# Create a simulate 50-word section from the model
index_text <- rep(0, 50)
index_text[1] <- sample(1 : length(b) - 50, size = 1)
for (i in 2 : 50){
  index_text[i] <- sample(1 : length(b), size = 1, prob = A[index_text[i - 1], ])
}
text <- b[index_text]

#Print out corresponding text
cat(text)
```

